default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
      - id: check-added-large-files
      - id: check-illegal-windows-names
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: check-vcs-permalinks
      - id: pretty-format-json
        args: [--no-sort-keys]
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-xml
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-ast
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        require_serial: true
